export const INITIALIZE_BOARD = 'INITIALIZE_BOARD';
export const SELECT_PIECE = 'SELECT_PIECE';
export const PLAY_TURN = 'PLAY_TURN';
export const SHOW_PAWN_PROMOTION_MODAL = 'SHOW_PAWN_PROMOTION_MODAL';
export const CANCEL_PAWN_PROMOTION_MODAL = 'CANCEL_PAWN_PROMOTION_MODAL';
export const RESTART_GAME = 'RESTART_GAME';